name: Deploy Minikube K8s App via Ansible

on:
  workflow_dispatch:

jobs:
  deploy-minikube-k8s-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}

      - name: Run Ansible Playbook for Minikube, Docker, and K8s App Setup
        run: |
          ansible-playbook -i "${{ secrets.SERVER_IP }}," minikube_k8s_app.yml -u ubuntu --private-key ~/.ssh/id_rsa
