on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: "Target server IP"
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ github.event.inputs.server_ip }} >> ~/.ssh/known_hosts

      - name: Clone App Repo on remote
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ github.event.inputs.server_ip }} "\
            git clone https://github.com/dheerendrabhandari8/terraform_assignment.git /home/ubuntu/terraform_assignment || true"

      - name: Docker login on remote
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ github.event.inputs.server_ip }} "\
            echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin"

      - name: Build & Push Docker image on remote
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ github.event.inputs.server_ip }} "\
            cd /home/ubuntu/terraform_assignment && \
            docker build -t dheerendrabhandari/nodejsapp:latest -f dockerfile/Dockerfile . && \
            docker push dheerendrabhandari/nodejsapp:latest"

      - name: Start Minikube on remote
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ github.event.inputs.server_ip }} "\
            minikube start --driver=docker || true"

      - name: Deploy Kubernetes manifests
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ github.event.inputs.server_ip }} "\
            cd /home/ubuntu/terraform_assignment && \
            kubectl apply -f k8s/"

      - name: Deploy Ingress controller (using Helm)
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ github.event.inputs.server_ip }} "\
            helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && \
            helm repo update && \
            helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx"

      - name: Expose test-app-deployment as NodePort service
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ github.event.inputs.server_ip }} "\
            kubectl expose deployment test-app-deployment --type=NodePort --name=test-app-service || true"

      - name: Get test-app-service URL
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ github.event.inputs.server_ip }} "\
            minikube service test-app-service --url || true"

      - name: Port forward test-app-service to localhost:3000
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ github.event.inputs.server_ip }} "\
            nohup kubectl port-forward svc/test-app-service 3000:3000 --address 0.0.0.0 &"
