on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  infra-and-install:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'ap-south-1' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Terraform steps as you already have

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan & Apply
        run: |
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

      - name: Output public IP
        id: output
        run: |
          echo "SERVER_IP=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ steps.output.outputs.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Run Ansible Install Playbook
        run: |
          ansible-playbook -i "${{ steps.output.outputs.SERVER_IP }},"ansible-playbook.yml -u ubuntu --private-key ~/.ssh/id_rsa
