name: Provision Infrastructure with Terraform

on:
  push:
    paths:
      - '**/*.tf'
      - '**/terraform.yml'
      - '**/terraform/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action: apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'ap-south-1' }}

    outputs:
      server_ip: ${{ steps.output.outputs.SERVER_IP }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event.inputs.action == 'apply'
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve

      - name: Output public IP
        if: github.event.inputs.action == 'apply'
        id: output
        run: echo "SERVER_IP=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

  configure:
    needs: terraform
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ needs.terraform.outputs.server_ip }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i "$SERVER_IP," ansible-playbook.yml -u ubuntu --private-key ~/.ssh/id_rsa

      - name: Build and Push Docker Image
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$SERVER_IP "\
            docker build -t dheerendrabhandari/nodejsapp:latest -f /home/ubuntu/terraform_assignment/docker/Dockerfile /home/ubuntu/terraform_assignment/docker && \
            echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin && \
            docker push dheerendrabhandari/nodejsapp:latest"

      - name: Start Minikube
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$SERVER_IP "\
            minikube start --driver=docker || true"

      - name: Install Ingress Controller
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$SERVER_IP "\
            helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && \
            helm repo update && \
            helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx"

      - name: Apply Kubernetes Manifests
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$SERVER_IP "\
            kubectl apply -f /home/ubuntu/terraform_assignment/deployment.yaml && \
            kubectl apply -f /home/ubuntu/terraform_assignment/service.yaml && \
            kubectl apply -f /home/ubuntu/terraform_assignment/ingress.yaml"

      - name: Expose NodePort Service (if needed)
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$SERVER_IP "\
            kubectl expose deployment test-app-deployment --type=NodePort --name=test-app-service || true"

      - name: Port Forward test-app-service (optional)
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$SERVER_IP "\
            nohup kubectl port-forward svc/test-app-service 3000:3000 --address 0.0.0.0 &"

