name: Provision and Deploy Infrastructure

on:
  push:
    paths:
      - '**/*.tf'
      - 'terraform.yml'
      - '**/terraform/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action: apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'ap-south-1' }}

    outputs:
      server_ip: ${{ steps.output.outputs.SERVER_IP }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve

      - name: Output public IP
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
        id: output
        run: echo "SERVER_IP=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

  ansible:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          SERVER_IP="${{ needs.terraform.outputs.server_ip }}"
          if [ -z "$SERVER_IP" ]; then
            echo "Server IP is empty. Exiting."
            exit 1
          fi
          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i "${{ needs.terraform.outputs.server_ip }}," ansible-playbook.yml -u ubuntu --private-key ~/.ssh/id_rsa

  deploy:
    needs: ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
#          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          SERVER_IP="${{ needs.terraform.outputs.server_ip }}"
          if [ -z "$SERVER_IP" ]; then
            echo "Server IP is empty. Exiting."
            exit 1
          fi
          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts

      - name: Clone App Repo on Remote
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ needs.terraform.outputs.server_ip }} "\
            git clone https://github.com/dheerendrabhandari8/terraform_assignment.git /home/ubuntu/terraform_assignment || true"

      - name: Docker login
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ needs.terraform.outputs.server_ip }} "\
            echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin"

      - name: Build & Push Docker Image
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ needs.terraform.outputs.server_ip }} "\
            docker build -t dheerendrabhandari/nodejsapp:latest -f /home/ubuntu/terraform_assignment/docker/Dockerfile /home/ubuntu/terraform_assignment/docker && \
            docker push dheerendrabhandari/nodejsapp:latest"

      - name: Start Minikube
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ needs.terraform.outputs.server_ip }} "minikube start --driver=docker"

      - name: Deploy Ingress Controller
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ needs.terraform.outputs.server_ip }} "\
            helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && \
            helm repo update && \
            helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx"

      - name: Deploy Kubernetes Manifests
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ needs.terraform.outputs.server_ip }} "\
            kubectl apply -f /home/ubuntu/terraform_assignment/k8s/"

      - name: Expose NodePort Service
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ needs.terraform.outputs.server_ip }} "\
            kubectl expose deployment test-app-deployment --type=NodePort --name=test-app-service || true"

      - name: Get Service URL
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ needs.terraform.outputs.server_ip }} "\
            minikube service test-app-service --url || true"

